// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAogokpV_iobWxUsY3jMf1DxzF4olYYUcA',
    appId: '1:469656910476:ios:c4c05504af48ce86f159a9',
    messagingSenderId: '469656910476',
    projectId: 'car-rental-management-sy-22c7f',
    databaseURL: 'https://car-rental-management-sy-22c7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-management-sy-22c7f.firebasestorage.app',
    iosBundleId: 'com.example.carrentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWCi7fvcfuZIEWeZfqOSVFvQncgXzf0kc',
    appId: '1:469656910476:web:24163549c1c6e4faf159a9',
    messagingSenderId: '469656910476',
    projectId: 'car-rental-management-sy-22c7f',
    authDomain: 'car-rental-management-sy-22c7f.firebaseapp.com',
    databaseURL: 'https://car-rental-management-sy-22c7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-management-sy-22c7f.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCi7fvcfuZIEWeZfqOSVFvQncgXzf0kc',
    appId: '1:469656910476:web:24163549c1c6e4faf159a9',
    messagingSenderId: '469656910476',
    projectId: 'car-rental-management-sy-22c7f',
    authDomain: 'car-rental-management-sy-22c7f.firebaseapp.com',
    databaseURL: 'https://car-rental-management-sy-22c7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-management-sy-22c7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogokpV_iobWxUsY3jMf1DxzF4olYYUcA',
    appId: '1:469656910476:ios:c4c05504af48ce86f159a9',
    messagingSenderId: '469656910476',
    projectId: 'car-rental-management-sy-22c7f',
    databaseURL: 'https://car-rental-management-sy-22c7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-management-sy-22c7f.firebasestorage.app',
    iosBundleId: 'com.example.carrentSystem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxnljKXp7xcAf5zEe3s23uB4Nlr6VTyU',
    appId: '1:469656910476:android:e7fc58e652737571f159a9',
    messagingSenderId: '469656910476',
    projectId: 'car-rental-management-sy-22c7f',
    databaseURL: 'https://car-rental-management-sy-22c7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-management-sy-22c7f.firebasestorage.app',
  );
}
